name: DEV

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main
env:
  GCLOUD_PROJECT: structure-codes
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate new templates.json
        run: node ./scripts/genList.js
      - name: Determine if any changes
        run: git diff --exit-code templates.json