name: DEV

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - setup-ci
env:
  GCLOUD_PROJECT: structure-codes
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate new templates.json
        run: node ./scripts/genList.js
      - name: If any new or changed template metadata, push it back to the repo
        run: |
          git diff --exit-code templates.json
          # If there are changes, run these steps
          if [ $? -eq 1 ]; then
            git add templates.json
            git commit -m "Automatically updating templates.json"
            git push
          fi